# Generated by Django 4.2.7 on 2023-11-28 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lastUpdate", models.DateTimeField(default=django.utils.timezone.now)),
                ("day", models.DateField()),
                ("hour_1", models.IntegerField()),
                ("hour_2", models.IntegerField()),
                ("hour_3", models.IntegerField()),
                ("hour_4", models.IntegerField()),
                ("hour_5", models.IntegerField()),
                ("hour_6", models.IntegerField()),
                ("hour_7", models.IntegerField()),
                ("hour_8", models.IntegerField()),
                ("hour_9", models.IntegerField()),
                ("hour_10", models.IntegerField()),
                ("hour_11", models.IntegerField()),
                ("hour_12", models.IntegerField()),
                ("hour_13", models.IntegerField()),
                ("hour_14", models.IntegerField()),
                ("hour_15", models.IntegerField()),
                ("hour_16", models.IntegerField()),
                ("hour_17", models.IntegerField()),
                ("hour_18", models.IntegerField()),
                ("hour_19", models.IntegerField()),
                ("hour_20", models.IntegerField()),
                ("hour_21", models.IntegerField()),
                ("hour_22", models.IntegerField()),
                ("hour_23", models.IntegerField()),
                ("hour_24", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.userprofile",
                    ),
                ),
            ],
        ),
    ]
