# Generated by Django 4.2.7 on 2023-11-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_userdata_hour_1_alter_userdata_hour_10_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="user.userprofile"
            ),
        ),
    ]
