# Generated by Django 4.2.7 on 2023-12-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_userdata_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="meterNumber",
        ),
        migrations.CreateModel(
            name="UserMeterNumbers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meterNumber", models.CharField(max_length=200)),
                (
                    "intitialReading",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                ("flag", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="user.userprofile",
                    ),
                ),
            ],
        ),
    ]
