# Generated by Django 4.2.7 on 2023-12-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_meterdata_usermeternumber_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermeternumber",
            old_name="intitialReading",
            new_name="initialReading",
        ),
        migrations.AlterField(
            model_name="usermeternumber",
            name="flag",
            field=models.IntegerField(default=1),
        ),
    ]
